spring:
  application:
    name: Revibe

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    generate-ddl: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        default_batch_fetch_size: 100
        enable_lazy_load_no_trans: true
        format_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  servlet:
    multipart:
      enabled: true
      max-request-size: 5MB
      max-file-size: 5MB


  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

logging:
  level:
    com:
      fasterxml:
        jackson:
          databind: info
    org:
      springframework:
        web: DEBUG

cloud:
  aws:
    credentials:
      secret-key: ${S3_SECRET_KEY}
      access-key: ${S3_ACCESS_KEY}

    region:
      static: ap-northeast-2

    s3:
      bucket: ${S3_BUCKET_NAME}

jwt:
  access:
    expiry-millis: 3600000
  refresh:
    expiry-millis: 40000000
  secret: ${JWT_SECRET_KEY}

kakao:
  client:
    id: ${KAKAO_ID}
    secret-key: ${KAKAO_SECRET_KEY}
    redirect-url: ${KAKAO_REDIRECT_URL}

toss:
  client-key: ${TOSS_CLIENT_KEY}
  secret-key: ${TOSS_SECRET_KEY}
  widget-key: ${TOSS_WIDGET_KEY}